application: shaonbarman
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: main.html
  upload: main.html

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /static
  static_dir: static
